version: '3.1'
services:

  neox-postgres:
    image: "postgres:12.0-alpine"
    restart: always
    container_name: neox-postgres    
    ports:
      - 5432:5432
    environment:    
      - POSTGRES_DB=neox_db
      - POSTGRES_USER=neox
      - POSTGRES_PASSWORD=neox
  